### PR TITLE
Code for Romania logo updated in login screen header

### PR DESCRIPTION
**Pull request by IvanSantosGonz**

### CODE REVIEW

**Review by AlexandraDaraban — CHANGES_REQUESTED** [review]
Looks good but there are some conflicts. Could you please solve them first?

**Comment by IvanSantosGonz** [comment]
ok I solved it

**Comment by AlexandraDaraban** [comment]
@IvanSantosGonz I think you forgot to push the commit

**Comment by IvanSantosGonz** [comment]
Solved in PR #62

**Comment by aniri** [comment]
> Solved in PR #62

Hey @IvanSantosGonz ! And thanks for your contribution! But please, in the future, try not to make two different pull requests for the same feature. You can commit and push changes to your branch even after making the pull request and the pull request gets automatically updated with the new changes. Thanks!

**Pull request merged**
