### PR TITLE
Enable screen for visited polling stations

### LINKED ISSUE #234: Show list of visited polling stations
- add new menu entry - 'My visited stations' / 'Secții de vot vizitate'
- selecting it would open a new screen with the list of visited polling stations (these should already be saved in the `polling_station` table), sort them by arrival date
- selecting a polling station from the list should take the user to the select polling station screen with the county and polling station number filled in
- _nice to have_: show the sync / not synced details on the bottom of this screen as well (they are currently displayed in the forms screen)

UI is available here: https://www.figma.com/file/lww9lcabUpamTZg8zCExI8/MV-2.0-Prototype?node-id=2%3A483

Visited_stations data not synced
visited stations synced

### LINKED ISSUE #235: Add link to polling stations list from choose polling station screen
**_depends on_** https://github.com/code4romania/mon-vot-android-kotlin/issues/234

It should be possible to navigate from the polling station chooser screen to the list of visited polling stations.

UI is available here: https://www.figma.com/file/lww9lcabUpamTZg8zCExI8/MV-2.0-Prototype?node-id=2%3A483

Choose polling station - with history

### PR DESCRIPTION
**Pull request by lukstbit**
### What does it fix?

Closes #234 
Closes #235 

This implements the visited polling stations UI and all the requests from the issue. For this I created a new activity, I wanted to reuse The PollingStationsActivity but it seemed difficult to incorporate it in the current code so I chose the easier solution. At this moment I'm making it a draft to discuss :
  - if this is the correct UI implementation
 - add other things to the code(like analytics?)
 - check the strings I used and add the proper icon for this new menu entry(I used the change polling station icon menu as a placeholder)

### How has it been tested?

Manually, as I created the UI.

### CODE REVIEW

**Comment by aniri** [comment]
Hey @lukstbit thanks! I'll test the implementation and get back on the UI part, just to answer your questions:

- the UI from figma shows also the new menu item https://www.figma.com/file/lww9lcabUpamTZg8zCExI8/MV-2.0-Prototype?node-id=371%3A415 , you can use that image for it :smiley: 

Menu with history

- nice catch! I'll think about needed analytics and add a separate issue with analytics for all newly added features :)

- if it is easier for you, you could also include #235 in this PR. I only made separate issues as they have different priorities and in case there wasn't time for implementing both

**Comment by lukstbit** [comment]
@aniri I don't have a Figma account so I can't access the icon(unless I'm missing something). Anyway this is a minor issue.

I pushed another commit with the implementation for #235

**Comment by aniri** [comment]
@lukstbit awesome! I just made a small commit with the icon from figma. It's faster like this :smile: 

I'll test everything tomorrow and let you know ;)

**Comment by aniri** [comment]
hey @lukstbit I've started testing the UI changes for these, I've found the following:

- the menu icon from the top should be visible in the visited stations screen
- the `>` icon is missing from the polling station item
- I think we can add a bit more vertical spacing between the polling station items
- we need to put in a scroll view since there could be more visited polling stations than they fit in the screen

**Comment by lukstbit** [comment]
I implemented the requested changes.

> the > icon is missing from the polling station item

I've left this out on purpose. Are you sure this should be implemented? A list item with an arrow to its right is a iOS UX pattern and not something really found/used in Android. If you do want to implement this tell me and also mention if the arrow button should have a special action.

**Comment by aniri** [comment]
> I implemented the requested changes.

@lukstbit Woooh! Looks awesome! :rocket: Just a nitpick though :/ could you put a menu icon in the visited section topbar instead of the back action? Just to keep it consistent with the other screens :smiley: 

> 
> > the > icon is missing from the polling station item
> 
> I've left this out on purpose. Are you sure this should be implemented? A list item with an arrow to its right is a iOS UX pattern and not something really found/used in Android. If you do want to implement this tell me and also mention if the arrow button should have a special action.

Good point! I'll get back to you on this, but I think we can ignore it :D

**Comment by aniri** [comment]
> I implemented the requested changes.
> 
> > the > icon is missing from the polling station item
> 
> I've left this out on purpose. Are you sure this should be implemented? A list item with an arrow to its right is a iOS UX pattern and not something really found/used in Android. If you do want to implement this tell me and also mention if the arrow button should have a special action.

@lukstbit ok, I got an ok from the UX team, there's no use for the arrow icon on android :D nice catch! thanks!

**Comment by aniri** [comment]
Also, one more nitpick :/ Would it be possible to hide the 'select from visited stations' text from the polling station details screen when first loading the app? Since it's a bit weird if there are no visited station added yet.

**Comment by lukstbit** [comment]
> could you put a menu icon in the visited section topbar instead of the back action? Just to keep it consistent with the other screens smiley

As I said in the first comment, I decided to use an Activity instead of a fragment because it was easier to implement. I can put an independent menu in the app bar but is not going to look/work good because it's another activity and the user will see clearly that he's using another "screen of the app". If it's a must I can refactor it into a fragment and plug it in the activity with the forms or with the polling stations selection but it is going to take time. Also, I want to point out that the menu doesn't appear in the polling station selection activity.

> ok, I got an ok from the UX team, there's no use for the arrow icon on android :D nice catch! thanks!

Imagine the outrage if the users would have seen that arrow :laughing: On a more serious note, yes I will implement disabling the station selection for the first time, there's no point for the user to see that when first starting.

**Comment by lukstbit** [comment]
@aniri The user will now not see the option to select from visited stations when he hasn't selected at least on station.

Also, I noticed something which doesn't seems right:

Go to forms screen -> select one form -> select a question -> choose an answer -> hit BACK(the system button) -> app makes an empty POST request to /answers(which is successful)-> the app shows the question with green(as answered). Are these answers registered on the backend? I'm asking this because if you select and answer multiple questions then hitting BACK it will make a POST request to /answers with all the answers except the last selected one(from the screen where we hit BACK).

The behavior seems inconsistent and could be a bug which makes us miss answers.

**Comment by aniri** [comment]
> As I said in the first comment, I decided to use an Activity instead of a fragment because it was easier to implement. I can put an independent menu in the app bar but is not going to look/work good because it's another activity and the user will see clearly that he's using another "screen of the app". If it's a must I can refactor it into a fragment and plug it in the activity with the forms or with the polling stations selection but it is going to take time. Also, I want to point out that the menu doesn't appear in the polling station selection activity.

Aaarghh, right. We already have the polling station selection activity with no menu. Yep, this will be tricky to refactor. But we'll keep it in mind for later :D For now it is perfect :smile: 

> Imagine the outrage if the users would have seen that arrow  

Madness! :rofl: 

> On a more serious note, yes I will implement disabling the station selection for the first time, there's no point for the user to see that when first starting.

Awesome, thanks! Also please mark this PR as ready for review after this last change :D I'll go through the code again for a quick check and then it can be merged :rocket:

**Comment by aniri** [comment]
> Also, I noticed something which doesn't seems right:
> 
> Go to forms screen -> select one form -> select a question -> choose an answer -> hit BACK(the system button) -> app makes an empty POST request to /answers(which is successful)-> the app shows the question with green(as answered). Are these answers registered on the backend? I'm asking this because if you select and answer multiple questions then hitting BACK it will make a POST request to /answers with all the answers except the last selected one(from the screen where we hit BACK).
> 
> The behavior seems inconsistent and could be a bug which makes us miss answers.

OMG, yes, it is a bug! The post request should send the answer in this case and not make an empty post :/ Nice catch! 

I'll add an issue for it!

**Review by aniri — APPROVED** [review]

**Pull request merged**
